// auto-generated
// Code generated by GUI builder.

package main

import (
	"fmt"

	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/widget"
)

type gui struct {
	win             fyne.Window
	Tags_path       string
	Annotation_path string
}

func newGUI(tagsPath, annotationPath string) *gui {
	return &gui{
		Tags_path:       tagsPath,
		Annotation_path: annotationPath,
	}
}

func (g *gui) makeUI() fyne.CanvasObject {

	return container.NewVBox(
		container.NewAppTabs(container.NewTabItem("Home",
			container.NewVBox()),
			container.NewTabItem("Metadata Explorer",
				container.NewVBox())),
		widget.NewRichTextFromMarkdown(fmt.Sprintf("Tags Path: %s", g.Tags_path)),
		widget.NewRichTextFromMarkdown(fmt.Sprintf("Annotation Folder: %s", g.Annotation_path)),
		widget.NewButton("Generate New Tags", g.generate_tags))
}

func (g *gui) makeWindow(a fyne.App) fyne.Window {
	w := a.NewWindow("main.gui.go")
	g.win = w
	w.Resize(fyne.NewSize(450, 319))
	w.SetContent(g.makeUI())
	return w
}
